pcl_topic: /cropbox/output
origin1: 30
origin2: -5
size1: 500
size2: 500
resolution: 0.2
out_pcl_topic: /my_elevation_map/pcl
map_frame: COSTAR_HUSKY/odom
rosbag: false

robot_size: 0.6


init_submap: true
init_submap_radius: 3.5
init_submap_height_offset: 0.12
init_submap_frame: COSTAR_HUSKY


traversability_topic: travers
slope_th: 0.2

vis_radius: 50

max_frontier_length: 5

# robot_base_frame_id:                        base_link
# robot_base_frame_id:                        COSTAR_HUSKY
# robot_pose_with_covariance_topic: "" # Leaving this empty skipps pose covariance updates.
# robot_pose_cache_size:                      200
# input_sources:
#   front: # A name to identify the input source
#     type: pointcloud # Supported types: pointcloud
#     topic: /cropbox/output #/COSTAR_HUSKY/points #/kiss_icp/kiss_icp_node/velodyne_pcl
#     queue_size: 1
#     publish_on_update: true # Wheter to publish the elevation map after a callback from this source.
#     sensor_processor:
#       type: perfect
#       ignore_points_above:       1.0
      

# track_point_frame_id:                       COSTAR_HUSKY/odom
# track_point_x:                              40
# track_point_y:                              -10
# track_point_z:                              0.0
# min_update_rate:                            4.0
# time_tolerance:                             1.0
# time_offset_for_point_cloud:                0.0
# # robot_motion_map_update/covariance_scale:   0.01

# # Map.
# length_in_x:                                50
# length_in_y:                                50
# position_x:                                 0
# position_y:                                 0
# resolution:                                 0.2
# min_variance:                               0.0001
# max_variance:                               0.05
# mahalanobis_distance_threshold:             2.5
# multi_height_noise:                         0.001
# surface_normal_positive_axis:               z
# fused_map_publishing_rate:                  10
# enable_visibility_cleanup:                  false
# visibility_cleanup_rate:                    1.0
# scanning_duration:                          1.0
# increase_height_alpha:                      0.95

# # Init submap
# initialize_elevation_map:                   true
# initialization_method:                      0
# length_in_x_init_submap:                    6
# length_in_y_init_submap:                    6
# init_submap_height_offset:                  -0.12
# init_submap_variance:                       0.01
# target_frame_init_submap:                   COSTAR_HUSKY