pcl_topic: /cropbox/output
origin1Offset: 30
origin2Offset: -5
size1: 500
size2: 500
resolution: 0.15
out_pcl_topic: /my_elevation_map/pcl
map_frame: COSTAR_HUSKY/odom
rosbag: false
odom_topic: /odom_gt

robot_size: 0.6

followWaypointTimeout: 20


init_submap: true
init_submap_radius: 3.5
init_submap_height_offset: 0.12
init_submap_frame: COSTAR_HUSKY


traversability_topic: travers
slope_th: 0.2

vis_radius: 50

max_frontier_length: 5
min_frontier_length: 1
explored_point_radius: 0.5
explorationRadius: 20

map_update_frequency: 100

# You can also tune other parameter, that can be found in include/subt_params.h